### ISSUE TITLE
转换未成功

### ISSUE THREAD

**Issue by opiater** [notonlyming/JsonToSRTCaption#1]
**序号2，转换未成功**

> Traceback (most recent call last):
>   File "/Users/username/Downloads/JsonToSRTCaption-master/main.py", line 25, in <module>
>     convert.main()
>   File "/Users/username/Downloads/JsonToSRTCaption-master/convert.py", line 147, in main
>     convent(FileName)
>   File "/Users/username/Downloads/JsonToSRTCaption-master/convert.py", line 121, in convent
>     captions = GetCapFromFile(FileName)
>   File "/Users/username/Downloads/JsonToSRTCaption-master/convert.py", line 34, in GetCapFromFile
>     captions = eval(f.read().replace('false','False').replace('true', 'True'))['captions']
> KeyError: 'captions'
> 程序发生了异常，请查看信息。（回车键退出）

**序号3，转换生成了json文件**

**Comment by notonlyming** [comment]
可能是你的 json 不是特定的 json，参见 sample.json 中的格式。其他 json 需要修改代码。另外，给出输入的 srt 实例？

**Comment by opiater** [comment]
json字幕文件是从b站提取的，方法来自[https://www.jianshu.com/p/66450e9554f8](url)，附文件之一[1.json.zip](https://github.com/notonlyming/JsonToSRTCaption/files/6139419/1.json.zip)

srt是从b站下载的bcc字幕转换而成的，附文件之一[1.srt.zip](https://github.com/notonlyming/JsonToSRTCaption/files/6139426/1.srt.zip)

**Comment by notonlyming** [comment]
json文件只支持示例的json格式。其它json结构需要自己修改代码。srt转换失误经排查是由于百度翻译返回的字符串经分割换行符后比源字符串少一个元素。可能是由于srt中的某些特定句子翻译有问题？我尝试删掉后面的大半部分，只保留了12000字以内以及6000字以内，分别被分成两部分或一部分。翻译成功了。推测可能是一个特定的srt的bug，也可能是翻译字符串部分太长出现问题，也可能是字符串分片的算法出现问题。看着就头痛，所以我不打算继续理这个bug了。从调试输出看来，你这个文档经过分片发送和翻译以后，翻译的效果非常差。因为该翻译的算法是把字幕的每一行都单独发送翻译，因此丢失了上下文信息。但是如果合起来翻译，涉及到中英语序的调整，翻译后的结果句子个数将会和原文不一致。又需要有代码进行断句的拆分。这是本项目的局限性。我不知道你的其它字幕还好不好。情况就是这么个情况，如果没有问题，我就关issue了。目前为止，代码对我要翻译的srt文件都工作良好。你可以继续寻找其它合适的项目，或继续使用（贡献）本项目。

**Comment by opiater** [comment]
只试了这一个字幕。明白情况了，关了吧，以后有机会再说吧。
